//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NT.UI.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NT.UI.MVC.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate step.
        /// </summary>
        internal static string activate_step {
            get {
                return ResourceManager.GetString("activate_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new attendent.
        /// </summary>
        internal static string add_attendant {
            get {
                return ResourceManager.GetString("add_attendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add conditional point.
        /// </summary>
        internal static string add_conditional {
            get {
                return ResourceManager.GetString("add_conditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new flow.
        /// </summary>
        internal static string add_flow {
            get {
                return ResourceManager.GetString("add_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new organisation.
        /// </summary>
        internal static string add_organisation {
            get {
                return ResourceManager.GetString("add_organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new organization member.
        /// </summary>
        internal static string add_organisation_member {
            get {
                return ResourceManager.GetString("add_organisation_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new platform.
        /// </summary>
        internal static string add_platform {
            get {
                return ResourceManager.GetString("add_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new project.
        /// </summary>
        internal static string add_project {
            get {
                return ResourceManager.GetString("add_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new step.
        /// </summary>
        internal static string add_step {
            get {
                return ResourceManager.GetString("add_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add subtheme.
        /// </summary>
        internal static string add_subtheme {
            get {
                return ResourceManager.GetString("add_subtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new platform.
        /// </summary>
        internal static string adding_platform {
            get {
                return ResourceManager.GetString("adding_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All employees.
        /// </summary>
        internal static string all_employees {
            get {
                return ResourceManager.GetString("all_employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All projects.
        /// </summary>
        internal static string all_projects {
            get {
                return ResourceManager.GetString("all_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answeroption.
        /// </summary>
        internal static string answeroption {
            get {
                return ResourceManager.GetString("answeroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        internal static string answers {
            get {
                return ResourceManager.GetString("answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We greatly appreciate your participation.
        ///  Thank you again!.
        /// </summary>
        internal static string appreciate {
            get {
                return ResourceManager.GetString("appreciate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a project.
        /// </summary>
        internal static string assign_project {
            get {
                return ResourceManager.GetString("assign_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned project.
        /// </summary>
        internal static string assigned_project {
            get {
                return ResourceManager.GetString("assigned_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendant details.
        /// </summary>
        internal static string attendant_details {
            get {
                return ResourceManager.GetString("attendant_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendant reassign.
        /// </summary>
        internal static string attendant_reassign {
            get {
                return ResourceManager.GetString("attendant_reassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendant name.
        /// </summary>
        internal static string attendant_name {
            get {
                return ResourceManager.GetString("attendant_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to theme selection.
        /// </summary>
        internal static string back_to_selection {
            get {
                return ResourceManager.GetString("back_to_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update conditional point .
        /// </summary>
        internal static string change_cp {
            get {
                return ResourceManager.GetString("change_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change state.
        /// </summary>
        internal static string change_state {
            get {
                return ResourceManager.GetString("change_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language.
        /// </summary>
        internal static string choice_language {
            get {
                return ResourceManager.GetString("choice_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose wich one do you want to have on this screen.
        /// </summary>
        internal static string choose_runningflow {
            get {
                return ResourceManager.GetString("choose_runningflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular.
        /// </summary>
        internal static string circular {
            get {
                return ResourceManager.GetString("circular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional point.
        /// </summary>
        internal static string conditional_points {
            get {
                return ResourceManager.GetString("conditional_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional steps.
        /// </summary>
        internal static string conditionele_steps {
            get {
                return ResourceManager.GetString("conditionele_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm changes.
        /// </summary>
        internal static string confirm_changes {
            get {
                return ResourceManager.GetString("confirm_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type.
        /// </summary>
        internal static string content_type {
            get {
                return ResourceManager.GetString("content_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a flow.
        /// </summary>
        internal static string create_flow {
            get {
                return ResourceManager.GetString("create_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new step.
        /// </summary>
        internal static string create_step {
            get {
                return ResourceManager.GetString("create_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string creation_date {
            get {
                return ResourceManager.GetString("creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate step.
        /// </summary>
        internal static string deactivate_step {
            get {
                return ResourceManager.GetString("deactivate_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete conditional point.
        /// </summary>
        internal static string delete_cp {
            get {
                return ResourceManager.GetString("delete_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete flow.
        /// </summary>
        internal static string delete_flow {
            get {
                return ResourceManager.GetString("delete_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete step.
        /// </summary>
        internal static string delete_step {
            get {
                return ResourceManager.GetString("delete_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete subtheme.
        /// </summary>
        internal static string delete_subtheme {
            get {
                return ResourceManager.GetString("delete_subtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string development {
            get {
                return ResourceManager.GetString("development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Development environment shouldn&apos;t be enabled for deployed applications.
        /// </summary>
        internal static string development_environment {
            get {
                return ResourceManager.GetString("development_environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        internal static string development_mode {
            get {
                return ResourceManager.GetString("development_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string email_adress {
            get {
                return ResourceManager.GetString("email_adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter credentials.
        /// </summary>
        internal static string enter_credentials {
            get {
                return ResourceManager.GetString("enter_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment will display more detailed information about the error that occurred.
        /// </summary>
        internal static string environment {
            get {
                return ResourceManager.GetString("environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment variable to.
        /// </summary>
        internal static string environment_variable {
            get {
                return ResourceManager.GetString("environment_variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        internal static string error_accured {
            get {
                return ResourceManager.GetString("error_accured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in contact.
        /// </summary>
        internal static string fill_in_contact {
            get {
                return ResourceManager.GetString("fill_in_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        internal static string flow {
            get {
                return ResourceManager.GetString("flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow details.
        /// </summary>
        internal static string flow_details {
            get {
                return ResourceManager.GetString("flow_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Enabled.
        /// </summary>
        internal static string flow_enable {
            get {
                return ResourceManager.GetString("flow_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow type.
        /// </summary>
        internal static string flow_type {
            get {
                return ResourceManager.GetString("flow_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flows.
        /// </summary>
        internal static string flows {
            get {
                return ResourceManager.GetString("flows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to receive further information?.
        /// </summary>
        internal static string further_info {
            get {
                return ResourceManager.GetString("further_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the step a name.
        /// </summary>
        internal static string give_name_step {
            get {
                return ResourceManager.GetString("give_name_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give it a theme.
        /// </summary>
        internal static string give_theme {
            get {
                return ResourceManager.GetString("give_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head theme.
        /// </summary>
        internal static string head_theme {
            get {
                return ResourceManager.GetString("head_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head theme description.
        /// </summary>
        internal static string head_theme_description {
            get {
                return ResourceManager.GetString("head_theme_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head theme name.
        /// </summary>
        internal static string head_theme_name {
            get {
                return ResourceManager.GetString("head_theme_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string home_page {
            get {
                return ResourceManager.GetString("home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image or Video.
        /// </summary>
        internal static string image_video {
            get {
                return ResourceManager.GetString("image_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about this project.
        /// </summary>
        internal static string info_project {
            get {
                return ResourceManager.GetString("info_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk mode .
        /// </summary>
        internal static string kiosk_mode {
            get {
                return ResourceManager.GetString("kiosk_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment.
        /// </summary>
        internal static string leave_comment {
            get {
                return ResourceManager.GetString("leave_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go.
        /// </summary>
        internal static string lets_go {
            get {
                return ResourceManager.GetString("lets_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear flow .
        /// </summary>
        internal static string lineair_flow {
            get {
                return ResourceManager.GetString("lineair_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        internal static string linear {
            get {
                return ResourceManager.GetString("linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendant.
        /// </summary>
        internal static string maintainer {
            get {
                return ResourceManager.GetString("maintainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make 1 choice.
        /// </summary>
        internal static string make_1_choice {
            get {
                return ResourceManager.GetString("make_1_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a conditional point.
        /// </summary>
        internal static string make_conditional_point {
            get {
                return ResourceManager.GetString("make_conditional_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make 1 or more choices.
        /// </summary>
        internal static string make_multiple_choice {
            get {
                return ResourceManager.GetString("make_multiple_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string mode {
            get {
                return ResourceManager.GetString("mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more information about other events!.
        /// </summary>
        internal static string more_info {
            get {
                return ResourceManager.GetString("more_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple choice.
        /// </summary>
        internal static string multiple_choice {
            get {
                return ResourceManager.GetString("multiple_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        internal static string no_info_available {
            get {
                return ResourceManager.GetString("no_info_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal mode.
        /// </summary>
        internal static string normal_mode {
            get {
                return ResourceManager.GetString("normal_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal steps.
        /// </summary>
        internal static string normal_steps {
            get {
                return ResourceManager.GetString("normal_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of assigned projects.
        /// </summary>
        internal static string number_project {
            get {
                return ResourceManager.GetString("number_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open question.
        /// </summary>
        internal static string open_question {
            get {
                return ResourceManager.GetString("open_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name.
        /// </summary>
        internal static string organization_name {
            get {
                return ResourceManager.GetString("organization_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned projects.
        /// </summary>
        internal static string owned_projects {
            get {
                return ResourceManager.GetString("owned_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to leave your details so we can provide you with more information about other events?.
        /// </summary>
        internal static string participate {
            get {
                return ResourceManager.GetString("participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauze   .
        /// </summary>
        internal static string pauze {
            get {
                return ResourceManager.GetString("pauze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauzed.
        /// </summary>
        internal static string pauzed {
            get {
                return ResourceManager.GetString("pauzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number: +32.
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project information.
        /// </summary>
        internal static string project_info {
            get {
                return ResourceManager.GetString("project_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string project_name {
            get {
                return ResourceManager.GetString("project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type.
        /// </summary>
        internal static string question_type {
            get {
                return ResourceManager.GetString("question_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range question.
        /// </summary>
        internal static string range_choice {
            get {
                return ResourceManager.GetString("range_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign.
        /// </summary>
        internal static string reassign {
            get {
                return ResourceManager.GetString("reassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * required.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and restarting the app.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string running {
            get {
                return ResourceManager.GetString("running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can result in displaying sensitive information from exceptions to end users.
        ///    For local debugging, enable the.
        /// </summary>
        internal static string sensitive_info {
            get {
                return ResourceManager.GetString("sensitive_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment by setting the.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description.
        /// </summary>
        internal static string short_description {
            get {
                return ResourceManager.GetString("short_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide table.
        /// </summary>
        internal static string show_hide_table {
            get {
                return ResourceManager.GetString("show_hide_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single choice.
        /// </summary>
        internal static string single_choice {
            get {
                return ResourceManager.GetString("single_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong :/.
        /// </summary>
        internal static string something_went_wrong {
            get {
                return ResourceManager.GetString("something_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Survey!.
        /// </summary>
        internal static string start_survey {
            get {
                return ResourceManager.GetString("start_survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        internal static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string step {
            get {
                return ResourceManager.GetString("step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        internal static string steps {
            get {
                return ResourceManager.GetString("steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit attendant details.
        /// </summary>
        internal static string submit_attendant {
            get {
                return ResourceManager.GetString("submit_attendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit organization member details.
        /// </summary>
        internal static string submit_organisation {
            get {
                return ResourceManager.GetString("submit_organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit personal details.
        /// </summary>
        internal static string submit_personal {
            get {
                return ResourceManager.GetString("submit_personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subthemes.
        /// </summary>
        internal static string subthemes {
            get {
                return ResourceManager.GetString("subthemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        internal static string survey {
            get {
                return ResourceManager.GetString("survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapping to.
        /// </summary>
        internal static string swapping_to {
            get {
                return ResourceManager.GetString("swapping_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for Participating in Phygital Tool!.
        /// </summary>
        internal static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thank You for Participating in Phygital Tool!.
        /// </summary>
        internal static string thank_you_participate {
            get {
                return ResourceManager.GetString("thank_you_participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme information.
        /// </summary>
        internal static string theme_info {
            get {
                return ResourceManager.GetString("theme_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme name.
        /// </summary>
        internal static string theme_name {
            get {
                return ResourceManager.GetString("theme_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes of.
        /// </summary>
        internal static string themes_of {
            get {
                return ResourceManager.GetString("themes_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Running.
        /// </summary>
        internal static string total_running {
            get {
                return ResourceManager.GetString("total_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock insights, ignite growth! Dive into our survey app today and let your voice be heard. 🚀 #SurveySuccess.
        /// </summary>
        internal static string unlock_insights {
            get {
                return ResourceManager.GetString("unlock_insights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update head theme.
        /// </summary>
        internal static string update_head_theme {
            get {
                return ResourceManager.GetString("update_head_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subtheme.
        /// </summary>
        internal static string update_subtheme {
            get {
                return ResourceManager.GetString("update_subtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the answeroptions.
        /// </summary>
        internal static string what_answeroption {
            get {
                return ResourceManager.GetString("what_answeroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What answeroption would you like to put the conditional point on:.
        /// </summary>
        internal static string what_answeroption_cp {
            get {
                return ResourceManager.GetString("what_answeroption_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What info would you like to share.
        /// </summary>
        internal static string what_info {
            get {
                return ResourceManager.GetString("what_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What question would you like to ask.
        /// </summary>
        internal static string what_question {
            get {
                return ResourceManager.GetString("what_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What step does it lead to.
        /// </summary>
        internal static string what_step {
            get {
                return ResourceManager.GetString("what_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the title.
        /// </summary>
        internal static string what_title {
            get {
                return ResourceManager.GetString("what_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account.
        /// </summary>
        internal static string your_account {
            get {
                return ResourceManager.GetString("your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string your_voice_matters {
            get {
                return ResourceManager.GetString("your_voice_matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string add_notes {
            get {
                return ResourceManager.GetString("add_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string stay_updated_q {
            get {
                return ResourceManager.GetString("stay_updated_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string stay_updated_a {
            get {
                return ResourceManager.GetString("stay_updated_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string no_update {
            get {
                return ResourceManager.GetString("no_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string fill_info_q {
            get {
                return ResourceManager.GetString("fill_info_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string fill_info_a {
            get {
                return ResourceManager.GetString("fill_info_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string step_name {
            get {
                return ResourceManager.GetString("step_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string created_by {
            get {
                return ResourceManager.GetString("created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string thank_you {
            get {
                return ResourceManager.GetString("thank_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string font {
            get {
                return ResourceManager.GetString("font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string primary_colour {
            get {
                return ResourceManager.GetString("primary_colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string select_colour {
            get {
                return ResourceManager.GetString("select_colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string buttons_infront {
            get {
                return ResourceManager.GetString("buttons_infront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string press_f {
            get {
                return ResourceManager.GetString("press_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string answer_mobile {
            get {
                return ResourceManager.GetString("answer_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string modal_title {
            get {
                return ResourceManager.GetString("modal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string end_session {
            get {
                return ResourceManager.GetString("end_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string flow_name {
            get {
                return ResourceManager.GetString("flow_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string flow_cannot_open {
            get {
                return ResourceManager.GetString("flow_cannot_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string flow_closed {
            get {
                return ResourceManager.GetString("flow_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string project_details {
            get {
                return ResourceManager.GetString("project_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string attendants {
            get {
                return ResourceManager.GetString("attendants", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string theme_details {
            get {
                return ResourceManager.GetString("theme_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string terug_project {
            get {
                return ResourceManager.GetString("terug_project", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string warning_cs {
            get {
                return ResourceManager.GetString("warning_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string terug_flow {
            get {
                return ResourceManager.GetString("terug_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string project_inactive {
            get {
                return ResourceManager.GetString("project_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string note_warning_subtheme {
            get {
                return ResourceManager.GetString("note_warning_subtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string closed_project {
            get {
                return ResourceManager.GetString("closed_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string no_assigned_flow {
            get {
                return ResourceManager.GetString("no_assigned_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string closed_flow {
            get {
                return ResourceManager.GetString("closed_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string no_step {
            get {
                return ResourceManager.GetString("no_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string no_note {
            get {
                return ResourceManager.GetString("no_note", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string required_birthday {
            get {
                return ResourceManager.GetString("required_birthday", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string test_flow {
            get {
                return ResourceManager.GetString("test_flow", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string add_conditional_step {
            get {
                return ResourceManager.GetString("add_conditional_step", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string least_characters {
            get {
                return ResourceManager.GetString("least_characters", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string uppcase_letter {
            get {
                return ResourceManager.GetString("uppcase_letter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string special_character {
            get {
                return ResourceManager.GetString("special_character", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string select_color {
            get {
                return ResourceManager.GetString("select_color", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Your voice matters.
        /// </summary>
        internal static string press_button {
            get {
                return ResourceManager.GetString("press_button", resourceCulture);
            }
        }
    }
}
